# Copyright 2020 pixiv Inc. All Rights Reserved.
#
# Use of this source code is governed by a license that can be
# found in the LICENSE.pixiv file in the root of the source tree.

env:
  DEPOT_TOOLS_UPDATE: '0'
  DEPOT_TOOLS_WIN_TOOLCHAIN: '0'

on:
  - push
  - pull_request

jobs:
  ios:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
        with:
          path: src
      - run: sudo xcode-select -s /Applications/Xcode_14.2.app/Contents/Developer
      - run: src/.github/bin/setup.ps1
      - run: gclient config --name=src --unmanaged "https://github.com/$GITHUB_REPOSITORY.git"
      - run: gclient sync --deps=ios,mac --no-history --shallow

      # The build option is expected to compatible with sora-ios-sdk.
      # rtc_enable_protobuf=false suppresses the event log, which consumes lots of memory,
      # for memory-constrained environment like broadcast extension.
      - run: src/tools_webrtc/ios/build_ios_libs.py --extra-gn-args rtc_enable_protobuf=false

      - run: zip -q -r --symlinks WebRTC.xcframework.zip WebRTC.xcframework
        working-directory: src/out_ios_libs

      - uses: actions/upload-artifact@v2
        with:
          name: ios
          path: src/out_ios_libs/WebRTC.xcframework.zip
